### ISSUE TITLE
Mention to click on the "Your Messages" button to see search bar

### ISSUE THREAD

**Issue by ultimatedelman** [trentmwillis/engine-training#1]
I just spent nearly an entire day uninstalling and reinstalling nearly everything on my computer trying to figure out why the search bar wouldn't show up. After going through the tutorial very, very closely for a second time, I decided to try to get _anything_ to show up in `mobile-app/app/templates/messaging/index.hbs` and was unable to. It then dawned on me after far too much time that I may just be in the wrong route and typed `messaging` into the url and lo and behold.

I think this is a critical, minor detail that should be included for future tutorial-takers.

**Comment by trentmwillis** [comment]
I took it for granted that since we were working with the `messaging` code that developers would navigate to the `/messaging` page. Will update.
